-- 결제 승인 내역. 서버의 service-role 키만 이 테이블에 기록·조회한다.
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  payment_key text not null,
  amount integer not null check (amount > 0),
  method text,
  status text not null,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

-- 브라우저 anon 키로 승인 상태를 위조할 수 없도록 한다.
alter table public.payments enable row level security;
